%% Example: analyze one intracranial LFP CSV
% Select a CSV interactively so this example works on any computer.

[fileName, fileDirectory] = uigetfile({'*.csv', 'LFP CSV files (*.csv)'}, ...
    'Select an LFP CSV file');
if isequal(fileName, 0)
    error('No CSV file was selected.');
end
inputFile = fullfile(fileDirectory, fileName);

% Fs is inferred as 1000 Hz from 180025 samples / 180 s.
% For formal analysis, explicitly supply the acquisition system's true Fs
% if it is known: 'SamplingRate', 1000.
results = analyze_lfp_csv(inputFile, ...
    'SamplingRate', 1000, ...
    'HighpassHz', 0.5, ...
    'LineNoiseHz', 50, ...
    'WindowSeconds', 4, ...
    'PSDMaxHz', 100, ...
    'FigureVisible', 'on');

disp(results.Metadata)
disp(results.SignalMetrics)
disp(results.BandPower)
disp(results.OutputFiles)

%% Example: custom bands
% customBands = table( ...
%     ["Delta"; "Theta"; "Alpha"; "Beta"; "Gamma"], ...
%     [1; 4; 8; 13; 30], [4; 8; 13; 30; 100], ...
%     'VariableNames', {'Band', 'Low_Hz', 'High_Hz'});
% results = analyze_lfp_csv(inputFile, 'SamplingRate', 1000, ...
%     'Bands', customBands, 'LineNoiseHz', 50);
