function [project, subjectTemplate, sessionTemplate, channelTemplate, runTemplate, comparisonTemplate] = lfp_project_schema()
%LFP_PROJECT_SCHEMA Return empty Project/Subject/Session templates.
%   The templates keep struct arrays homogeneous across MATLAB releases and
%   centralize the schema used by project management and migration helpers.

project = struct( ...
    'schema_version', 4, 'storage_mode', "legacy_root", 'project_id', "", 'name', "", 'description', "", 'rootPath', "", ...
    'createdAt', "", 'updatedAt', "", 'defaultConfig', struct(), ...
    'subjects', struct([]), 'analysisRuns', struct([]), 'comparisons', struct([]), ...
    'paths', struct('index', "project.mat", 'data', "data", ...
        'results', "results", 'comparisons', "comparisons", ...
        'subjects', "subjects", 'exports', "exports", 'logs', "logs"), ...
    'migrationLog', struct([]));

subjectTemplate = struct('subject_id', "", 'display_name', "", 'group', "", ...
    'notes', "", 'folder_relative_path', "", 'sessions', struct([]));
sessionTemplate = struct('session_id', "", 'subject_id', "", 'visit_label', "", ...
    'acquisition_date', "", 'medication_state', "", 'stimulation_state', "", ...
    'repeat_label', "", 'notes', "", 'data_version', "", 'data_refs', struct([]), ...
    'channels', struct([]), 'analysis_run_ids', strings(0, 1), 'status', "imported", ...
    'folder_relative_path', "");
channelTemplate = struct('channel_id', "", 'original_label', "", ...
    'display_label', "", 'side', "", 'region', "", 'contacts', "", ...
    'reference', "", 'unit', "", ...
    'session_id', "", 'source_file_id', "", 'source_column', NaN, ...
    'sampling_rate_hz', NaN, 'sample_count', 0, 'time_start', NaN, ...
    'time_end', NaN, 'cache_relative_path', "", 'enabled', true, ...
    'data_revision', "", 'quality_status', "unassessed", ...
    'source_metadata', struct());
runTemplate = struct('run_id', "", 'session_id', "", 'input_data_version', "", ...
    'channel_ids', strings(0, 1), 'channel_labels', strings(0, 1), ...
    'analysis_time_range', [NaN NaN], 'config', struct(), 'config_id', "", ...
    'software_version', "", 'created_at', "", 'module_status', struct(), ...
    'result_ref', "", 'summary', struct(), 'status', "pending", 'warnings', strings(0, 1), ...
    'channel_results', struct([]));
comparisonTemplate = struct('comparison_id', "", 'type', "custom", ...
    'subject_ids', strings(0, 1), 'session_ids', strings(0, 1), ...
    'visit_label', "", 'channel_mapping', struct([]), 'channel_entries', struct([]), 'metric', "totalPower", ...
    'bands', strings(0, 1), 'target_config_id', "", 'aggregation', "session", ...
    'plot_settings', struct(), 'run_ids', strings(0, 1), 'created_at', "", ...
    'status', "pending", 'warnings', strings(0, 1), 'result_table', table(), ...
    'grouping_basis', "", 'group_defs', struct([]), 'subject_count', 0, ...
    'session_count', 0, 'psd_summary', struct());
% Complete nested array types after all templates exist.
dataRefTemplate = struct('relative_path', "", 'source_path', "", ...
    'project_copy_relative_path', "", ...
    'source_file_name', "", 'segment_id', "", 'sample_count', 0, ...
    'channel_count', 0, 'fs', NaN, 'time_start', NaN, 'time_end', NaN, ...
    'channel_labels', strings(0,1), 'channel_ids', strings(0,1), ...
    'cache_relative_paths', strings(0,1), 'source_file_id', "", ...
    'source_file_fingerprint', "", 'import_config', struct(), ...
    'time_unit', "s", 'signal_unit', "", 'imported_at', "", ...
    'cache_version', "1");
sessionTemplate.channels = channelTemplate([]);
sessionTemplate.data_refs = dataRefTemplate([]);
subjectTemplate.sessions = sessionTemplate([]);
% Replace untyped empty arrays in the project template with homogeneous
% arrays.  This matters when appending the first record in MATLAB.
project.subjects = subjectTemplate([]);
project.analysisRuns = runTemplate([]);
project.comparisons = comparisonTemplate([]);
end
